"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { api, ReportListItem } from "@/lib/api";

export default function ReportsPage() {
  const [reports, setReports] = useState<ReportListItem[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api
      .listReports()
      .then(setReports)
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  return (
    <div className="max-w-4xl mx-auto p-6 space-y-6">
      <div>
        <h1 className="text-xl font-semibold text-gray-900">AI Analysis Reports</h1>
        <p className="text-sm text-gray-400 mt-1">
          Reports generated by the multi-agent ReACT analysis engine
        </p>
      </div>

      {loading ? (
        <div className="text-center py-12">
          <div className="w-8 h-8 border-2 border-gray-200 border-t-purple-600 rounded-full animate-spin mx-auto mb-3" />
          <p className="text-sm text-gray-400">Loading reports...</p>
        </div>
      ) : reports.length === 0 ? (
        <div className="bg-white rounded-xl border border-gray-200 p-12 text-center">
          <div className="text-4xl mb-4 opacity-20">&#128196;</div>
          <p className="text-sm text-gray-500 mb-2">No reports yet</p>
          <p className="text-xs text-gray-400">
            Run a scenario simulation or consensus analysis to generate your first report
          </p>
          <div className="flex justify-center gap-3 mt-4">
            <Link
              href="/scenarios"
              className="text-xs bg-purple-600 text-white px-4 py-2 rounded-lg hover:bg-purple-500 transition-colors"
            >
              Run Scenario
            </Link>
          </div>
        </div>
      ) : (
        <div className="space-y-3">
          {reports.map((report) => (
            <div
              key={report.id}
              className="bg-white rounded-xl border border-gray-200 p-5 hover:shadow-sm transition-shadow"
            >
              <div className="flex items-start justify-between">
                <div className="min-w-0 flex-1">
                  <div className="flex items-center gap-2 mb-1">
                    <span className="text-lg">&#128196;</span>
                    <h3 className="text-sm font-semibold text-gray-900 truncate">
                      {report.scenario_description
                        ? `Scenario: ${report.scenario_description.substring(0, 80)}`
                        : `${report.simulation_type} Analysis`}
                    </h3>
                  </div>
                  <div className="flex items-center gap-3 text-xs text-gray-400">
                    <span
                      className={`px-2 py-0.5 rounded-full ${
                        report.status === "completed"
                          ? "bg-emerald-50 text-emerald-600"
                          : "bg-amber-50 text-amber-600"
                      }`}
                    >
                      {report.status}
                    </span>
                    <span className="capitalize">{report.simulation_type.replace("_", " ")}</span>
                    {report.completed_at && (
                      <span>{new Date(report.completed_at).toLocaleDateString()}</span>
                    )}
                  </div>
                </div>

                <div className="flex gap-2 ml-4 shrink-0">
                  {report.report_id && (
                    <>
                      <Link
                        href={`/reports/${report.report_id}`}
                        className="text-xs bg-purple-600 text-white px-3 py-1.5 rounded-lg hover:bg-purple-500 transition-colors"
                      >
                        Read Report
                      </Link>
                    </>
                  )}
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
